[package]
name = "asciituber"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = { version = "4.4", features = [ "derive" ] }
image = "0.24"
imageproc = "0.23"
rand = "0.8"
rscam = "0.5"
rusttype = "0.9"
