[package]
name = "asciituber"
version = "0.1.0"
edition = "2021"

[dependencies]
ab_glyph = "0.2"
anyhow = "1.0"
clap = { version = "4.5", features = [ "derive" ] }
image = "0.25"
imageproc = "0.24"
rand = "0.8"
rscam = "0.5"
